name: Continuous Integration

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

env:
  DOTNET_VERSION: '10.0.103'
  BUILD_CONFIGURATION: 'Release'

jobs:
    build:
      name: "CI"
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Set up .NET 
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: ${{env.DOTNET_VERSION}}        
        
        - name: Test
          run: dotnet test --configuration ${{env.BUILD_CONFIGURATION}}

        - name: Dotnet Publish
          run: dotnet publish src/TaskApi/TaskApi.csproj --configuration ${{env.BUILD_CONFIGURATION}} -o artifacts

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: uv-artifact
            path: artifacts/

    deploy_dev:
      name: Deploy Dev
      runs-on: ubuntu-latest
       
      steps:
          - name: Download Artifact
            uses: actions/download-artifact@v4
            with:
              name: uv-artifact
              path: artifacts/

